version: '3.8'
services:
  postgres:
    image: postgres:15.1
    ports:
      - 5534:5432
    volumes:
      - /data/postgres:/data/postgres
    networks:
      - currency-api

  currency_api:
    # image: currency_api
    command: start
    build: 
      context: ./
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - currency-api

volumes:
  postgres:
    name: nest-init-docker-db

networks:
  currency-api:
    driver: bridge
